/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.program;

import javax.swing.DefaultListModel;
import jdbc.service.MySQLMahasiswaService;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import jdbc.model.Mahasiswa;



/**
 *
 * @author kemal
 */
public class JFrameUtama extends javax.swing.JFrame {
    
    private MySQLMahasiswaService service;
    private DefaultListModel<String> modelID;
    private DefaultListModel<String> modelNama;

    /**
     * Creates new form JFrameUtama
     */
    public JFrameUtama() {
        initComponents();
        
        service = new MySQLMahasiswaService();
        modelID = new DefaultListModel<>();
        modelNama = new DefaultListModel<>();
        
        jListID.setModel(modelID);
        jListName.setModel(modelNama);
        
        setupListSelectionListener();
    }
    
    private void refreshListData() {
        try {
            modelID.clear();
            modelNama.clear();
            
            for (Mahasiswa mhs : service.getAll()) {
                modelID.addElement(String.valueOf(mhs.getId()));
                modelNama.addElement(mhs.getNama());
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data: " + e.getMessage());
        }
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelListID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListID = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListName = new javax.swing.JList<>();
        jLabelListName = new javax.swing.JLabel();
        jLabelKelolaDataMahasiswa = new javax.swing.JLabel();
        jButtonAmbilSemuaData = new javax.swing.JButton();
        jLabelTextFieldName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jButtonTambahkanName = new javax.swing.JButton();
        jTextFieldIDEdit = new javax.swing.JTextField();
        jTextFieldNamaEdit = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jTextFieldIDDelete = new javax.swing.JTextField();
        jTextFieldNameDelete = new javax.swing.JTextField();
        jButtonDelete = new javax.swing.JButton();
        jButtonResetIndex = new javax.swing.JButton();
        jLabelIndexReset = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelListID.setText("ID");

        jListID.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListID);

        jListName.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListName);

        jLabelListName.setText("NAMA");

        jLabelKelolaDataMahasiswa.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabelKelolaDataMahasiswa.setText("Kelola Data Mahasiswa");
        jLabelKelolaDataMahasiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButtonAmbilSemuaData.setText("Ambil Semua Data");
        jButtonAmbilSemuaData.addActionListener(this::jButtonAmbilSemuaDataActionPerformed);

        jLabelTextFieldName.setText("Nama:");

        jButtonTambahkanName.setText("Tambahkan");
        jButtonTambahkanName.addActionListener(this::jButtonTambahkanNameActionPerformed);

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(this::jButtonEditActionPerformed);

        jButtonDelete.setText("Hapus");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jButtonResetIndex.setText("Reset Indeks");
        jButtonResetIndex.addActionListener(this::jButtonResetIndexActionPerformed);

        jLabelIndexReset.setText("Indeks direset ke 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelListID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelListName)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldName)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldIDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNamaEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEdit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldIDDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNameDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAmbilSemuaData)
                            .addComponent(jLabelKelolaDataMahasiswa)
                            .addComponent(jLabelTextFieldName)
                            .addComponent(jButtonTambahkanName))
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonResetIndex)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelIndexReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelListID)
                    .addComponent(jLabelListName)
                    .addComponent(jLabelKelolaDataMahasiswa))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAmbilSemuaData)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTextFieldName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTambahkanName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNamaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIDDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNameDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonResetIndex)
                            .addComponent(jLabelIndexReset))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupListSelectionListener() {
        javax.swing.event.ListSelectionListener listener = e -> {
            if (!e.getValueIsAdjusting()) {
                int index = jListID.getSelectedIndex();
                if (index == -1) {
                    index = jListName.getSelectedIndex();
                }
                
                if (index != -1) {
                    String id = modelID.getElementAt(index);
                    String nama = modelNama.getElementAt(index);
                    jTextFieldIDEdit.setText(id);
                    jTextFieldNamaEdit.setText(nama);
                    jTextFieldIDDelete.setText(id);
                    jTextFieldNameDelete.setText(nama);
                }
            }
        };
        
        jListID.addListSelectionListener(listener);
        jListName.addListSelectionListener(listener);
        
        jListID.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListName.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }
    private void jButtonAmbilSemuaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmbilSemuaDataActionPerformed
        // TODO add your handling code here:
        refreshListData();
    }//GEN-LAST:event_jButtonAmbilSemuaDataActionPerformed

    private void jButtonTambahkanNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahkanNameActionPerformed
        // TODO add your handling code here:
        String nama = jTextFieldName.getText().trim();
        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!");
            return;
        }
        
        try {
            Mahasiswa mhs = new Mahasiswa(0, nama);
            service.add(mhs);
            
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
            refreshListData();
            jTextFieldName.setText("");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menambah: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButtonTambahkanNameActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        String idStr = jTextFieldIDEdit.getText().trim();
        String nama = jTextFieldNamaEdit.getText().trim();
        
        if (idStr.isEmpty() || nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID dan Nama harus diisi!");
            return;
        }
        
        try {
            int id = Integer.parseInt(idStr);
            Mahasiswa mhs = new Mahasiswa(id, nama);
            service.update(mhs);
            
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
            refreshListData();
            jTextFieldIDEdit.setText("");
            jTextFieldNamaEdit.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID harus berupa angka!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengupdate: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        String idStr = jTextFieldIDDelete.getText().trim();
        
        if (idStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID harus diisi!");
            return;
        }
        
        try {
            int id = Integer.parseInt(idStr);
            service.delete(id);
            
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            refreshListData();
            jTextFieldIDDelete.setText("");
            jTextFieldNameDelete.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID harus berupa angka!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonResetIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetIndexActionPerformed
        // TODO add your handling code here:
        try {
            service.indexReset();
            JOptionPane.showMessageDialog(this, "Indeks berhasil direset!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal reset indeks: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonResetIndexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAmbilSemuaData;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonResetIndex;
    private javax.swing.JButton jButtonTambahkanName;
    private javax.swing.JLabel jLabelIndexReset;
    private javax.swing.JLabel jLabelKelolaDataMahasiswa;
    private javax.swing.JLabel jLabelListID;
    private javax.swing.JLabel jLabelListName;
    private javax.swing.JLabel jLabelTextFieldName;
    private javax.swing.JList<String> jListID;
    private javax.swing.JList<String> jListName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldIDDelete;
    private javax.swing.JTextField jTextFieldIDEdit;
    private javax.swing.JTextField jTextFieldNamaEdit;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNameDelete;
    // End of variables declaration//GEN-END:variables
}
